# Generated by Django 3.1.3 on 2020-11-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201122_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyheader',
            name='is_active',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
