# Generated by Django 3.1.3 on 2020-11-23 06:46

from django.db import migrations, models
import pages.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20201122_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyheader',
            name='coimage',
            field=models.ImageField(null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[pages.validators.validate_number]),
        ),
    ]
