# Generated by Django 3.1.3 on 2020-11-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201123_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyheader',
            name='is_active',
            field=models.BooleanField(default=True, null=True, unique=True),
        ),
    ]
