# Generated by Django 3.1.3 on 2020-11-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201123_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyheader',
            name='google_embed',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
