# Generated by Django 3.1.3 on 2020-11-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_companyheader_google_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyheader',
            name='google_embed',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
