# Generated by Django 3.1.3 on 2020-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=200)),
                ('main_background_image', models.ImageField(null=True, upload_to='service/')),
                ('sub_heading', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('box_image', models.ImageField(null=True, upload_to='service/')),
                ('heading_title', models.TextField(max_length=20)),
                ('description_title', models.TextField(blank=True)),
                ('box_image1', models.ImageField(null=True, upload_to='service/')),
                ('heading_title1', models.TextField(max_length=20)),
                ('description_title1', models.TextField(blank=True)),
                ('box_image2', models.ImageField(null=True, upload_to='service/')),
                ('heading_title2', models.TextField(max_length=20)),
                ('description_title2', models.TextField(blank=True)),
                ('main_image', models.ImageField(null=True, upload_to='service/')),
                ('sub_heading_title', models.TextField(max_length=20)),
                ('sub_description_title', models.TextField(blank=True)),
                ('sub_heading_title1', models.TextField(max_length=20)),
                ('sub_description_title1', models.TextField(blank=True)),
                ('question', models.TextField(max_length=20)),
                ('answer', models.TextField(blank=True)),
                ('question1', models.TextField(max_length=20)),
                ('answer1', models.TextField(blank=True)),
                ('question2', models.TextField(max_length=20)),
                ('answer2', models.TextField(blank=True)),
                ('question3', models.TextField(max_length=20)),
                ('answer3', models.TextField(blank=True)),
                ('question4', models.TextField(max_length=20)),
                ('answer4', models.TextField(blank=True)),
                ('list_info', models.TextField(max_length=20)),
                ('list_info1', models.TextField(max_length=20)),
            ],
        ),
    ]
