# Generated by Django 3.1.3 on 2020-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='heading_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='heading_title1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='heading_title2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='list_info',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='question',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='question1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='question2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='question3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='question4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_heading_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_heading_title1',
            field=models.CharField(max_length=20),
        ),
    ]
