# Generated by Django 3.1.3 on 2020-11-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20201124_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='list_info',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='list_info1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='question',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='question1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='question2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='question3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='question4',
            field=models.CharField(max_length=50),
        ),
    ]
