# Generated by Django 3.1.3 on 2020-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201125_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='list_info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='list_info1',
            field=models.CharField(max_length=100),
        ),
    ]
